language: ruby
os: linux
dist: xenial
rvm:
  - 2.6.3

env:
  global:
    # deploy host
    - secure: "dUZDoueBuzIiYo8A3YVxTfsrrbKN2Gm2i/WjOJt5p9ZGzOnv4/cBxgs6UquKykZyMzmEFqqhutrV9ECR8vEgMZr6uXx4wpjqtlDa9cn5kewiL2K8tmW+6b9W1VSK8/Ki2HyR7tmDxf3Skd9xBbg/G6m3ghhxXrsH96fGMQp8CFUvukzsXuvEKrxE2Y/JGLROVaIyAXLwBZ9Amw/jvZLUhHJ9vtVKTAXDm/OxTfuJCh0j0plOB1z+Ob+KHaSug+VHKqld0PbeTf3JWdv3P3Y94j1drAy2zU/bkaTzsooQOAG2uZhNIwEZ2PiKttWJe1zqhg9q3Hj0bi+9yj7iQIus8QFudqPQssiV0oBu6HFYxLwl99kfuqK2KOBD/e2Ixjy70y9gzT5ViMYw+jEh+AQviglmyh97Cit0xHbihCHWaHwaTgu3qtN+0IUnPwPNKhCgAbZ9twcepa9QfyXPe1UTnd7z0jZqxr4BmAlxDsbsnYL1sUnspYf2fBGzysTNX6iU8YtTBZT1McLrBZ6EgIDGT+dAY8657AZ120MsOVnpycPWrAv4reNW1e6X6XZIhXpvFStU3euuSIs2HHI8gafi1opOxJHqGnP+Q9+7pHlDnuxCe73KIRXbBPPe3cZauzwMugq2duJbzev9AtQLFY6arUCY2kWQ0jCFEfKBvzuR3Vk="
    # deploy path
    - secure: "asw5qgygB4RFvvw8nO+UmCVde/tn7jkwtodp/wKrCdbaAnluc4X/M0PQaTRB7Kw+83vhqUjtwwJ2Io1dGJgjoeYAx4OPH59dFlYg6zqxD4v+lU+Qzan/ZHs4cKuOTzQjvqj01uwK00KpT6McykB16awD1OOfU89pLDN6tQGtQyS1G5n4YuJNQOO9CuQjQdmik8PYKC1TQII64xtKGXcS28IFm4jCFk7Dp+khRJ8Gg1wOOgeO/KKPPI5UgvNtp/Ph+b+GhvW5MuNU5H6cvLs2yTELx4tBYcr60YOl/tGG58EaRtB1032C5aMV2gpejByCt7uMjtb9PueibShpMDiSr3rnKvcmsz/g3xT624wzF8pNOmKWrbLbHLAaXRsfYTHPM6rd9eLspaytQKbczK5m7nrhpIbVrh/mx51Wyx68dme/f/AUuB8DVZiIKkYdCFzW8PrmMQJxqHt2/ryKMCf7MLMKCQHsI2hGNY4Tb9EXup/b5i9e7wjh4dYiBLUkEhS0Im0j9lvMP0sRrWfYDc/1tfCru8kWnT7QojZVQRHi1aIzAQK4N8qCZ0w3gs2VFR6yJqHHqpXBiJnee6AVGmfyRVc9VN7SRdyBFnnk1ba+7R7W1HMZfyPypDwXfPbbhTLCKonYTGsPgFS3/o4Bp1U5Kmyc1zRFyPm8paDKQg9Dg2g="
    # deploy user
    - secure: "TMGX4CrZbDv5LiM7oGa7JagVAqpyeCbIDown5aKCWJZEoUemYuKqDuebHHkPGGR4wvTbKEx9As57ww50MEWaSGiVHLU+OlGawlaIHpYONknNI98ZlPMa5oLV7oxSHDooL3ra3bLLdmx9SUXNnXLtgnffCI2r2uvMu1ST97JETWKX6L0GC+WrEp5twYMa7afeEAsPQNtE8LwRvQkncac3X3w2ur9Ugz0XR24KSjaQqGrYZowQzTm1r7d3UlJ8fL8Gh/r12EVhvf1mW690H376WYzbZSci3cL+zYwbN0nD2uoACLWnM9irb2dxZ0lHXq1Ap+igy5kJqu9+/PjYpS7aU/fcGEm/rf6DuWua4jvd9upiAfjkfzQaqr0r1Wav+XZqz2jowqazzuResu5ZEZCqvDKmAuJV6dO3sDY/X/tMI2Qz6tmtxJHSSUWwpP4FtxVJEPPjQ8cQzvcXZz0z50+V0jBeK9i7ZeqO7ZtNVf/PS2H4iuCDwQOhe1uJmr8TmD5dRFY7r2YYBWkcKyPHR0LqIWlgIikuJceLjRfjryTzUfL4TS3Y6JSWnKkoCh0r5NbwwURrKbqTeTEcHz+Mb4iMU2DClBiU+Q/odi38IPdWpO57MS3C+owTLvPOQfkTfbeU6dZQWbccHcqBu5joSkaFWK3XTdIupY7bIQ8beUC9pZk="
    # deploy pass
    - secure: "akclFY40aYjly/Lp6Qyk2gSb70+nagaWs7HzEqI6rdMM6KvHx+dMA6KFp4QvsQGnQvJy1npzm5xv+hoEu1ChgCuyQ2klSF07dPSQRvax8Jox+y70+JNkvQd+x6XWwALGw8CI5vkSuFnF+Ua1xDgm0WSLiyOVLdfPSsLZd/2DDgzrzzwcl1gGtoEg0vgCR1Jz9BREaW76UzDy9JgIGPyANFp+ub9Nv456q1KtzBgBXb7VDqVRRxhRnF/qCphD93D36haRehc2+CvLKZ4vVxrYK7jVSR51tJHW4OZhSZccwe70JbFlbiQ8oWfc3/Ucsl1OwJG7pYg7n+rXa0b3aofF78HlOezn5zDKS0IpzmTJjX4ekP1ivGAD9UI9hGYKBEpVFVu6V5Pcn7evw0N40hLXkQlQ97UQyH15mKIdEH+bNKiStwspxqbNhp/9vrRGcX+fIKiW7D+2jRt5yU6sEJdcnJOTjFbniaYhHLdE5Amgvp1/BMmI3ykRXr0sCJbWhg0aR10TRSfNum8WNuG5LxeXhr69NFucS4wCYANTc7bPB98DO6B5hipAPtkfe8PROL0126knMlHWU9VEz3czc3ei2Wug0Iz8cQ1cWakzNj1Oy6wl/UJixcRsecjhdhoaS7TkxcGhq4Vg+aU+W/k0p16IVemNjGunDM4885Ig5TFb/Xk="

addons:
  apt:
    packages:
      - sshpass

cache: bundler # caching bundler gem packages will speed up build

before_script:
  - chmod +x ./assets/script/cibuild.sh
  - chmod +x ./assets/script/deploy.sh

# Assume bundler is being used, therefore
# the 'install' step will run 'bundle install' by default.
# Will run HTMLProofer + Jekyll Build
script: ./assets/script/cibuild.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./assets/script/deploy.sh $DEPLOY_HOST $DEPLOY_PATH $DEPLOY_USER $DEPLOY_PASS
  # on:
  #   branch: main

# after_success:
#   - tar -czf package.tgz _site
#   - export SSHPASS=$DEPLOY_PASS
#   - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
#   - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
#   - rm package.tgz

# Optional: disable email notifications about the outcome of your build
notifications:
  email:
    recipients:
     - baguiov@posteo.net
    on_success: never
    on_failure: always